package HelloWorldApp;


/**
* HelloWorldApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Helloworld.idl
* Friday, October 24, 2025 11:50:43 AM WET
*/

public interface HelloOperations 
{
  String HelloMessage ();
  void HelloMessage (String newHelloMessage);
} // interface HelloOperations
