package HelloWorldApp;


/**
* HelloWorldApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Helloworld.idl
* Friday, October 24, 2025 11:50:43 AM WET
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
